# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '18.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'My Company',
    'depends': [
        'maintenance',
        'stock',
        'web_grid',
        'web_hierarchy',
        'web_studio',
        'website',
    ],
    'data': [
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_default.xml',
    ],
    'license': 'OPL-1',
}
